kwc_menuapi.root:
    path:       /api/v1/kwc-menu
    defaults:
        _controller: kwc_menuapi.menu_controller:getComponentsAction

kwc_menuapi.component:
    path:       /api/v1/kwc-menu/{componentId}
    defaults:
        _controller: kwc_menuapi.menu_controller:getComponentAction
