kwf_kwcnativemenu.root:
    path:       /api/v1/native-menu
    defaults:
        _controller: kwf_kwcnativemenu.menu_controller:getComponentsAction

kwf_kwcnativemenu.component:
    path:       /api/v1/native-menu/{componentId}
    defaults:
        _controller: kwf_kwcnativemenu.menu_controller:getComponentAction
