services:
    kwf_kwcnativemenu.menu_controller:
        class:    Kwf\KwcNativeMenuBundle\Controller\MenuController
        autowire: true

    kwf_kwcnativemenu.components:
        class:    Kwf\KwcNativeMenuBundle\Services\Components
        autowire: true
