services:
    kwc_menuapi.menu_controller:
        class:    Kwc\MenuApiBundle\Controller\MenuController
        autowire: true

    kwc_menuapi.components:
        class:    Kwc\MenuApiBundle\Services\Components
        autowire: true
